---
- name: make sure monitor_interface or monitor_address or monitor_address_block is configured
  fail:
    msg: "Either monitor_interface, monitor_address, or monitor_address_block must be configured. Interface for the monitor to listen on or IP address of that interface"
  when:
    - monitor_interface == 'interface'
    - monitor_address == '0.0.0.0'
    - monitor_address_block == 'subnet'

- name: make sure pg num is set for cephfs pools
  fail:
    msg: "You must set pg num for your cephfs pools, see the cephfs_pools variable."
  with_items: "{{ cephfs_pools }}"
  when:
    - groups.get(mds_group_name, []) | length > 0
    - item.pgs == ''

- name: test bucket types are valid, if any
  fail:
    msg: "Valid CRUSH bucket types are {{ valid_crush_bucket_list }}."
  with_items: "{{ groups[osd_group_name] }}"
  when:
    - crush_rule_config
    - hostvars[item]['ceph_crush_room'] ('default_rack_' + hostvars[item]['ceph_crush_root']) is defined
